# Generated by Django 3.1.3 on 2021-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='image',
            field=models.ImageField(default='images/book-open.png', upload_to='books_img'),
        ),
    ]
