# Generated by Django 3.1.3 on 2021-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210312_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='image',
            field=models.ImageField(default='static/images/book-open.png', upload_to='books_img'),
        ),
    ]
